### PR TITLE
Add visualization code

### PR DESCRIPTION
**Pull request by mdml**
Add an initial draft of visualization code, all of which lives in `viz/`. See `README.md` for instructions for setup and usage.

I tested by generating JSON files for COADREAD and UCEC, and then visualizing these results.

### CODE REVIEW

**Comment by matthewreyna** [comment]
I tested the visualizations, and they provide a very nice view of the results! Below are several notes:
1. I used the following sequence of commands on Ubuntu:
   
   ```
   # Install NodeJS and NPM with apt-get:
   sudo apt-get install nodejs npm
   # Avoid the following error on some Linux distributions:
   #     /usr/bin/env: node: No such file or directory
   sudo ln -s /usr/bin/nodejs /usr/bin/node 
   # Install Bower with NPM:
   sudo npm install -g bower
   ```
2. I needed to compile CoMEt before running `python generate_viz_data.py`.  We also need to compile CoMEt before running the saddlepoint approximation code.  Let's be either (1) more selective about when we import modules or (2) allow the import to fail silently and only raise an exception when we actually need the module -- preferably the first option.
3. We should explain the arguments for `generate_viz_data.py` and `server.py` in the README.
4. The results table visualization worked great, except that p-values were sorted lexicographically (1.00862e-1, 1.13451e-7, 1.15411e-3, ...) instead of numerically.
5. The mutation matrix and mutation probabilities visualizations did not appear in the visualization, but the input file for `server.py` contained mutation probabilities from the mutation probability matrix.

I can provide the input files for debugging.

**Comment by mdml** [comment]
(1) Please add these to the wiki.

(2) What do you mean "you need to compile CoMEt"? CoMEt is not a dependency. All you need to do is run `python setup.py build`, which is (and IMHO should be) required before running anything.

(3) I disagree. I vote this should be in the wiki.

(4) Good point! I will fix.

(5) Can you finish your thought here?

**Comment by matthewreyna** [comment]
(1) Will do.

(2) By "compile CoMEt", I mean that we need to run `python setup.py build`, which compiles C code for CoMEt and the exact version of the weighted exclusivity test.  However, the saddlepoint approximation, for example, and the visualization code do not depend on these things, so why require them?  Yes, we should run `python setup.py build` first, but why require it?  This is an easy fix, so I don't see the downside.

(3) I agree.  By README, I of course meant the wiki.  Let's point the reader more directly to the wiki in the README.

(4) Good!

(5) Finished.

**Comment by braphael8** [comment]
I am not looking at the visualizations, but from your example of output, it
seems that there are too many significant digits for the p-values.  I don't
see a point in showing more than 3-4 significant digits 1.xxE-y  or
1.xxxE-y.

**Comment by mdml** [comment]
@braphael8: I was using 5 significant digits, I can change to 3 if you prefer.

**Comment by mdml** [comment]
@matthewreyna I just pushed changes that should fix (4) and (5), and use 3 significant digits. Please review.

**Comment by matthewreyna** [comment]
I updated `bower.json` to fix a problem cloning `gd3` on my machine.  It works well!  This includes the visualizations of the mutation matrix and mutation probability matrix, which failed to show earlier.

Small details, such as truncating the values on the colorbar for the mutation probability matrix and updating the mouse-over text for the entries of the mutation probability matrix (something like `x: some sample \n y: some gene \n value : 0.86753098675309` to `Sample: ABC \n Gene: DEF \n Probability : 8.675e-1`), are all that remain for now.

**Comment by matthewreyna** [comment]
Small issue: for the probability matrix visualization, the colorbar is inconsistent with the colors in the matrix, e.g., light blue might indicate a probability of 0.001 in the probability matrix, but the same shade of light blue might indicate a probability of 0.6 in the corresponding colorbar.  Also, it would be good to add a third value to the colorbar to show more clearly whether the colors have a linear or logarithmic progression from light to dark.

Also, in the Gene Pair visualization section, please change both instances of "pair" to "set."

**Pull request merged**
